Anaxar's
AdamrePL/Project pull request #13
Opened 2024-04-15 12:03 UTC by Anaxar1

2024-04-15 12:21 UTC, derfiedev approved these changes

2024-04-15 13:00 UTC, AdamrePL commented
hah. widze ze w pliku booklist.php jednak zrezygnowales z sidebaru

2024-04-15 13:01 UTC, AdamrePL approved these changes
balls.

2024-04-15 23:25 UTC, chopa113 reviewed
@Anaxar1 nie pracuj na moim kodzie, masz mojego pull requesta z fixem każdego baga w dodawaniu nowej oferty

2024-04-15 23:26 UTC, chopa113 requested changes
nie merguj zmian mojego kody

2024-04-16 07:38 UTC, Anaxar1 commented
Przecież nie wprowadzam tam jakichś wielkich zmian, poza tym jest kilka rzeczy do poprawienia związanych z frontendem więc będę musiał coś zmienić.

2024-04-16 10:13 UTC, AdamrePL approved these changes
Idc go ahead

2024-04-16 12:57 UTC, derfiedev approved these changes

2024-04-17 09:05 UTC, closed without merging